package br.com.vercel.emerionloadservice.client.dto

import java.math.BigDecimal
import java.time.LocalDate

data class CustomerIngestionDto(
    val externalId: Long,
    val cnpjEmpresa: String,
    val nomeFantasia: String,
    val razaoSocial: String,
    val cpfCnpj: String,
    val inscricaoEstadual: String?,
    val regimeTributario: String?,
    val bloqueado: Boolean,
    val dataNascimento: LocalDate?,
    val dataCadastro: LocalDate?,
    val dataUltimaAtualizacao: LocalDate?,
    val email1: String?,
    val email2: String?,
    val website: String?,
    val limiteCredito: BigDecimal?,
    val observacoes: String?,
    val cnae: String?,
    val vendedorExternalId: Long?,
    val nomeVendedor: String?,
    val codigoTipoCliente: String?,
    val codigoGrupoCliente: String?,
    val codigoCategoriaCliente: String?,
    val uf: String?,
    val macroRegiao: String?,
    val microRegiao: String?,
    val setor: String?,

    val faturamentoCep: String?,
    val faturamentoTipoEndereco: String?,
    val faturamentoEndereco: String?,
    val faturamentoNumero: String?,
    val faturamentoComplemento: String?,
    val faturamentoBairro: String?,
    val faturamentoCidade: String?,
    val faturamentoUf: String?,
    val faturamentoDDDTelefone: String?,
    val faturamentoTelefone: String?,
    val faturamentoDDDFax: String?,
    val faturamentoFax: String?,
    val faturamentoContato: String?,
    val faturamentoDDDCelular: String?,
    val faturamentoCelular: String?,

    val cobrancaCep: String?,
    val cobrancaTipoEndereco: String?,
    val cobrancaEndereco: String?,
    val cobrancaNumero: String?,
    val cobrancaComplemento: String?,
    val cobrancaBairro: String?,
    val cobrancaCidade: String?,
    val cobrancaUf: String?,
    val cobrancaDDDTelefone: String?,
    val cobrancaTelefone: String?,
    val cobrancaDDDFax: String?,
    val cobrancaFax: String?,
    val cobrancaContato: String?,
    val cobrancaDDDCelular: String?,
    val cobrancaCelular: String?,

    val entregaCep: String?,
    val entregaTipoEndereco: String?,
    val entregaEndereco: String?,
    val entregaNumero: String?,
    val entregaComplemento: String?,
    val entregaBairro: String?,
    val entregaCidade: String?,
    val entregaUf: String?,
    val entregaDDDTelefone: String?,
    val entregaTelefone: String?,
    val entregaDDDFax: String?,
    val entregaFax: String?,
    val entregaContato: String?,
    val entregaDDDCelular: String?,
    val entregaCelular: String?
)
