package br.com.vercel.emerionloadservice.client.dto

import java.math.BigDecimal

data class ProductIngestionDto(
    val externalId: String,
    val cnpjEmpresa: String,
    val nome: String,
    val descricaoReduzida: String?,
    val referenciaInterna: String?,
    val ncm: String?,
    val cest: String?,
    val origemProduto: String?,
    val categoria: String?,
    val tipo: String?,
    val marca: String?,
    val unidadeEntrada: String?,
    val unidadeSaida: String?,
    val pesoLiquido: BigDecimal?,
    val pesoBruto: BigDecimal?,
    val descontinuado: Boolean?,
    val codigoBarras: String?,
    val codigoBarrasProprio: String?,
    val preco: BigDecimal?,
    val preco2: BigDecimal?,
    val preco3: BigDecimal?,
    val preco4: BigDecimal?,
    val preco5: BigDecimal?,
    val descontoPadrao: BigDecimal?,
    val estoqueDisponivel: BigDecimal?,
    val estoqueMinimo: BigDecimal?,
    val estoqueMaximo: BigDecimal?,
    val estoqueReservado: BigDecimal?,
    val estoqueAdquirido: BigDecimal?,
    val estoqueAtual: BigDecimal?,
    val estoqueRMA: BigDecimal?,
    val simpro: String?,
    val quantidadeVolumes: BigDecimal?,
    val quantidadeEmbalagem: BigDecimal?,
    val locpro: String?,
    val pescub: BigDecimal?,
    val cbaemb: String?,
    val ibsCClassTrib: String?,
    val ibsCst: String?,
    val fcpEntrada: String?,
    val fcpSaida: String?,
    val ipiSaida: String?,
    val ipiEntrada: String?,
    val icmSaida: String?,
    val icmEntrada: String?,
    val icmStSaida: String?,
    val icmStEntrada: String?,
    val saiicm: String?,
    val enticm: String?,
    val codst2: String?,
    val observacao: String?
)
