server:
  port: 8181

spring:
  application:
    name: emerion-load-service

  datasource:
    driver-class-name: org.firebirdsql.jdbc.FBDriver
    hikari:
      connection-timeout: 2000
      maximum-pool-size: 5
    url: jdbc:firebirdsql://127.0.0.1:3050//data//portal_2024_01.fdb
    username: SYSDBA
    password: masterkey

  jpa:
    hibernate:
      ddl-auto: validate
    database-platform: org.hibernate.community.dialect.FirebirdDialect

ingestion-service:
  base-url: http://localhost:8080
  endpoints:
    customer: /api/v1/ingestion/customers/single
    product: /api/v1/ingestion/products/single
    customer-address: /api/v1/ingestion/customer-addresses/single
    customer-credit: /api/v1/ingestion/customer-credits/batch
    customer-order: /api/v1/ingestion/customer-orders/single