package br.com.vercel.emerionloadservice.client.mapper

import br.com.vercel.emerionloadservice.api.model.CustomerOrderIngestionDto
import br.com.vercel.emerionloadservice.api.model.CustomerOrderItemIngestionDto
import br.com.vercel.emerionloadservice.model.CustomerOrder
import br.com.vercel.emerionloadservice.model.CustomerOrderItem

object CustomerOrderIngestionMapper {
    // The receiving service generates its own internal id, so the order business key
    // is sent as externalId to keep cross-company and cross-date uniqueness.
    fun CustomerOrder.toIngestionDto(cnpjEmpresa: String): CustomerOrderIngestionDto =
        CustomerOrderIngestionDto(
            externalId = "${this.codigoEmpresa}.${this.dataPedido}.${this.numeroPedido}",
            codigoEmpresa = this.codigoEmpresa,
            codigoCliente = this.codigoCliente,
            cnpjEmpresa = cnpjEmpresa,
            customerExternalId = this.codigoCliente,
            dteres = this.dataPedido.toLocalDate(),
            cpfCnpj = this.cpfCnpj,
            numeroPedido = this.numeroPedido,
            dataPedido = this.dataPedido,
            statusPedido = this.statusPedido,
            totalPedidoComImpostos = this.totalPedidoComImpostos,
            totalPedidoSemImpostos = this.totalPedidoSemImpostos,
            totalIpi = this.totalIpi,
            totalIcms = this.totalIcms,
            totalPis = this.totalPis,
            totalCofins = this.totalCofins,
            totalSubstituicaoTributaria = this.totalSubstituicaoTributaria,
            totalDescontoIncondicional = this.totalDescontoIncondicional,
            totalFrete = this.totalFrete,
            totalSeguro = this.totalSeguro,
            totalOutrasDespesas = this.totalOutrasDespesas,
            vendedorExternalId = this.vendedorExternalId,
            dataEntregaPrevista = this.dataEntregaPrevista,
            codigoTransportadora = this.codigoTransportadora,
            pedidoAnterior = this.pedidoAnterior,
            regimeTributario = this.regimeTributario,
            nomeRegimeTributario = this.nomeRegimeTributario,
            codigoPadraoFaturamento = this.codigoPadraoFaturamento,
            itens = this.itens.map { it.toIngestionDto() },
        )

    private fun CustomerOrderItem.toIngestionDto(): CustomerOrderItemIngestionDto =
        CustomerOrderItemIngestionDto(
            codEmp = this.codEmp,
            dteres = this.dteres,
            numres = this.numres,
            produto = this.produto,
            descricao = this.descricao,
            quantidade = this.quantidade,
            valorUnitario = this.valorUnitario,
            valorTotal = this.valorTotal,
            seqRe2 = this.seqRe2,
            codClp = this.codClp,
            codSt1 = this.codSt1,
            codUnd = this.codUnd,
            vluRe2 = this.vluRe2,
            dscRe2 = this.dscRe2,
            dsrRe2 = this.dsrRe2,
            icmsAliquota = this.icmsAliquota,
            icmsBase = this.icmsBase,
            icmsValor = this.icmsValor,
            icmsReducaoBase = this.icmsReducaoBase,
            icmsSubstituicaoBase = this.icmsSubstituicaoBase,
            icmsSubstituicaoValor = this.icmsSubstituicaoValor,
            icmsSubstituicaoAliquota = this.icmsSubstituicaoAliquota,
            icmsSubstituicaoMargem = this.icmsSubstituicaoMargem,
            icmsSubstituicaoReducaoBase = this.icmsSubstituicaoReducaoBase,
            ipiAliquota = this.ipiAliquota,
            ipiBase = this.ipiBase,
            ipiValor = this.ipiValor,
            ipiClassificacao = this.ipiClassificacao,
            ipiCst = this.ipiCst,
            pisBase = this.pisBase,
            pisAliquota = this.pisAliquota,
            pisValor = this.pisValor,
            pisCst = this.pisCst,
            cofinsBase = this.cofinsBase,
            cofinsAliquota = this.cofinsAliquota,
            cofinsValor = this.cofinsValor,
            cofinsCst = this.cofinsCst,
            descontoValor = this.descontoValor,
            freteValor = this.freteValor,
            seguroValor = this.seguroValor,
            outrasDespesasValor = this.outrasDespesasValor,
            totalItemTributado = this.totalItemTributado,
            totRen = this.totRen,
            totGe2 = this.totGe2,
            observacao = this.observacao,
            pedidoCompraCliente = this.pedidoCompraCliente,
            itemPedidoCompraCliente = this.itemPedidoCompraCliente,
            nroRe2 = this.nroRe2,
            flgVal = this.flgVal,
            flgPac = this.flgPac,
            flgLib = this.flgLib,
            codCfo = this.codCfo,
            codcor = this.codcor,
            codtam = this.codtam,
            descricaoNFe = this.descricaoNFe,
            pesoLiquido = this.pesoLiquido,
            pesoBruto = this.pesoBruto,
            referencia = this.referencia,
            quantidadeFaturada = this.quantidadeFaturada,
            quantidadeSeparada = this.quantidadeSeparada,
            custoTotal = this.custoTotal,
            lucroValor = this.lucroValor,
            lucroPorcentagem = this.lucroPorcentagem,
            saldoQuantidade = this.saldoQuantidade,
            descontoItemValor = this.descontoItemValor,
            descontoItemTotal = this.descontoItemTotal,
        )
}
