CREATE TABLE FINCLI (
                        CODCLI             INTEGER NOT NULL,
                        NOMCLI             VARCHAR(70),
                        APECLI             VARCHAR(20),
                        INSCLI             VARCHAR(18),
                        CGCCLI             VARCHAR(18),
                        DTNCLI             DATE,
                        LIMCLI             NUMERIC(15,2),
                        TIPCLI             CHAR(1),
                        FLBCLI             CHAR(1),
                        CEFCLI             CHAR(8),
                        TEFCLI             VARCHAR(10),
                        ENFCLI             VARCHAR(70),
                        RFFCLI             VARCHAR(40),
                        NRFCLI             VARCHAR(10),
                        BAFCLI             VARCHAR(20),
                        CIFCLI             VARCHAR(20),
                        UFFCLI             CHAR(2),
                        CEACLI             CHAR(8),
                        TEACLI             VARCHAR(10),
                        ENACLI             VARCHAR(70),
                        RFACLI             VARCHAR(40),
                        NRACLI             VARCHAR(10),
                        BAACLI             VARCHAR(20),
                        CIACLI             VARCHAR(20),
                        UFACLI             CHAR(2),
                        CEECLI             CHAR(8),
                        TEECLI             VARCHAR(10),
                        ENECLI             VARCHAR(70),
                        RFECLI             VARCHAR(40),
                        NRECLI             VARCHAR(10),
                        BAECLI             VARCHAR(20),
                        CIECLI             VARCHAR(20),
                        UFECLI             CHAR(2),
                        INECLI             VARCHAR(18),
                        CGECLI             VARCHAR(18),
                        COMCLI             VARCHAR(40),
                        CECCLI             CHAR(8),
                        TECCLI             VARCHAR(10),
                        ENCCLI             VARCHAR(70),
                        RFCCLI             VARCHAR(40),
                        NRCCLI             VARCHAR(10),
                        BACCLI             VARCHAR(20),
                        CICCLI             VARCHAR(20),
                        UFCCLI             CHAR(2),
                        PT1CLI             VARCHAR(4),
                        FO1CLI             VARCHAR(20),
                        PT2CLI             VARCHAR(4),
                        FO2CLI             VARCHAR(20),
                        PT3CLI             VARCHAR(4),
                        FO3CLI             VARCHAR(20),
                        PF1CLI             VARCHAR(4),
                        FA1CLI             VARCHAR(20),
                        PF2CLI             VARCHAR(4),
                        FA2CLI             VARCHAR(20),
                        PF3CLI             VARCHAR(4),
                        FA3CLI             VARCHAR(20),
                        OBSCLI             VARCHAR(2000),
                        DCACLI             DATE,
                        CODUSU             INTEGER,
                        CODVEN             INTEGER,
                        CODATD             INTEGER,
                        CODGCL             INTEGER,
                        CODBAN             INTEGER,
                        CODTRA             INTEGER,
                        CODCCL             INTEGER,
                        CODTCL             INTEGER,
                        CODCOM             VARCHAR(3),
                        CODMCR             INTEGER,
                        CODMRG             INTEGER,
                        CODSET             INTEGER,
                        CODMST             INTEGER,
                        DTLCRE             DATE,
                        INCPAG             CHAR(1),
                        CLITAB             VARCHAR(23),
                        CLIDEV             NUMERIC(15,2),
                        FLGTRG             CHAR(1),
                        COFCLI             VARCHAR(40),
                        COCCLI             VARCHAR(40),
                        COECLI             VARCHAR(40),
                        PT4CLI             VARCHAR(4),
                        FO4CLI             VARCHAR(20),
                        PF4CLI             VARCHAR(4),
                        FA4CLI             VARCHAR(20),
                        NROSUF             VARCHAR(20),
                        FLGPSQ             CHAR(3),
                        DTEACM             DATE,
                        TOTACM             NUMERIC(15,2) DEFAULT 0,
                        DTEATU             DATE,
                        HREATU             CHAR(8),
                        USUATU             INTEGER,
                        MUNSUF             INTEGER,
                        TENCOB             VARCHAR(21),
                        TENCOM             VARCHAR(21),
                        TENENT             VARCHAR(21),
                        FLGPRO             CHAR(3),
                        CODPFA             VARCHAR(15),
                        TIPPFA             VARCHAR(15),
                        FLGINF             CHAR(3),
                        CODREP             INTEGER,
                        FLGCA1             CHAR(3),
                        FLGCA2             CHAR(3),
                        INCPAL             CHAR(3),
                        CODPAL             INTEGER,
                        FLGCA3             CHAR(3),
                        FLGINT             CHAR(3),
                        DTVSUF             DATE,
                        DCALIM             DATE,
                        HRELIM             CHAR(8),
                        USULIM             INTEGER,
                        DATLIM             DATE,
                        HRALIM             CHAR(8),
                        USALIM             INTEGER,
                        QTDICL             INTEGER DEFAULT 0,
                        PC1CLI             CHAR(4),
                        FC1CLI             CHAR(20),
                        PC2CLI             CHAR(4),
                        FC2CLI             CHAR(20),
                        PC3CLI             CHAR(4),
                        FC3CLI             CHAR(20),
                        PC4CLI             CHAR(4),
                        FC4CLI             CHAR(20),
                        ID_FINHOL          INTEGER,
                        ID_FINUFF          INTEGER,
                        ID_FINCIF          INTEGER,
                        ID_FINUFA          INTEGER,
                        ID_FINCIA          INTEGER,
                        ID_FINUFE          INTEGER,
                        ID_FINCIE          INTEGER,
                        ID_FINUFC          INTEGER,
                        ID_FINCIC          INTEGER,
                        MENBL1             VARCHAR(80),
                        MENBL2             VARCHAR(80),
                        MENBL3             VARCHAR(80),
                        MENBL4             VARCHAR(80),
                        MENBL5             VARCHAR(80),
                        MENCR1             VARCHAR(80),
                        MENCR2             VARCHAR(80),
                        MENCR3             VARCHAR(80),
                        MENCR4             VARCHAR(80),
                        MENCR5             VARCHAR(80),
                        ID_FINPAI          INTEGER,
                        EM1CLI             VARCHAR(70),
                        EM2CLI             VARCHAR(70),
                        EM3CLI             VARCHAR(70),
                        WEBCLI             VARCHAR(70),
                        ID_FINCTB          INTEGER,
                        ID_FINCT2          INTEGER,
                        ID_FINCT3          INTEGER,
                        ID_FINCT4          INTEGER,
                        ID_FINCT5          INTEGER,
                        ID_FINCT6          INTEGER,
                        CRE_DEV_USU        INTEGER,
                        CRE_DEV_OBS        VARCHAR(200),
                        CRE_DEV_DTE        DATE,
                        TIPO_PESSOA        CHAR(2),
                        REGTRB             INTEGER,
                        INDIC_ESTRANGEIRO  VARCHAR(20),
                        INDIC_IE           INTEGER DEFAULT 0,
                        INSC_MUNICIPAL     CHAR(15),
                        CNAE               CHAR(20),
                        CEST               CHAR(7),
                        EMAIL_INTERNO_XML  CHAR(60),
                        OBSFIN             VARCHAR(2000)
);
ALTER TABLE FINCLI ADD CONSTRAINT FINCLI_PK PRIMARY KEY (CODCLI);
CREATE TABLE ESTPRO
(
    CODCLP INTEGER NOT NULL,
    CODGRU INTEGER NOT NULL,
    CODSUB INTEGER NOT NULL,
    CODPRO INTEGER NOT NULL,
    DESCRI VARCHAR(100),
    CONSTRAINT PK_ESTPRO
        PRIMARY KEY (CODCLP, CODGRU, CODSUB, CODPRO)
);

CREATE TABLE PEDRES
(
    CODEMP INTEGER NOT NULL,
    DTERES DATE    NOT NULL,
    NUMRES INTEGER NOT NULL,
    CODCLI INTEGER NOT NULL,
    VALTOT DECIMAL(15, 2),

    CONSTRAINT PK_PEDRES
        PRIMARY KEY (CODEMP, DTERES, NUMRES),

    CONSTRAINT FK_PEDRES_FINCLI
        FOREIGN KEY (CODCLI)
            REFERENCES FINCLI (CODCLI)
);

CREATE TABLE PEDRE2
(
    CODEMP     INTEGER NOT NULL,
    DTERES     DATE    NOT NULL,
    NUMRES     INTEGER NOT NULL,
    SEQRE2     INTEGER NOT NULL,

    CODCLP     INTEGER NOT NULL,
    CODGRU     INTEGER NOT NULL,
    CODSUB     INTEGER NOT NULL,
    CODPRO     INTEGER NOT NULL,

    CODTAM     INTEGER,
    CODCOR     INTEGER,

    QUANTIDADE DECIMAL(15, 3),

    CONSTRAINT PK_PEDRE2
        PRIMARY KEY (CODEMP, DTERES, NUMRES, SEQRE2),

    CONSTRAINT FK_PEDRE2_PEDRES
        FOREIGN KEY (CODEMP, DTERES, NUMRES)
            REFERENCES PEDRES (CODEMP, DTERES, NUMRES),

    CONSTRAINT FK_PEDRE2_ESTPRO
        FOREIGN KEY (CODCLP, CODGRU, CODSUB, CODPRO)
            REFERENCES ESTPRO (CODCLP, CODGRU, CODSUB, CODPRO)
);


CREATE TABLE GEREMP (
                        CODEMP     INTEGER,
                        CEPEMP     CHAR(8),
                        ENDEMP     VARCHAR(40),
                        REFEMP     VARCHAR(20),
                        TENEMP     VARCHAR(10),
                        NUMEMP     VARCHAR(10),
                        BAIEMP     VARCHAR(20),
                        CIDEMP     VARCHAR(20),
                        SIGUFE     CHAR(2),
                        CGCEMP     VARCHAR(18),
                        INSEMP     VARCHAR(18),
                        PRTEMP     VARCHAR(4),
                        PRFEMP     VARCHAR(4),
                        EMAEMP     VARCHAR(50),
                        WEBEMP     VARCHAR(50),
                        QTDNFS     INTEGER DEFAULT 0,
                        NUMRES     INTEGER,
                        NUMPED     INTEGER,
                        FLSGER     CHAR(1),
                        FLGTRG     CHAR(1),
                        CODFIL     INTEGER,
                        LANEST     CHAR(3),
                        LANCAI     CHAR(3),
                        FLGPRE     CHAR(3),
                        EXIEST     CHAR(3),
                        QTDACP     INTEGER DEFAULT 0,
                        EXIEMP     CHAR(3),
                        FLGSER     CHAR(3),
                        FLGFIL     CHAR(3),
                        NFSLOJ     INTEGER DEFAULT 0,
                        NOMEMP     CHAR(60),
                        APEEMP     CHAR(30),
                        QTDNOT     INTEGER DEFAULT 0,
                        FONEMP     CHAR(30),
                        FAXEMP     CHAR(30),
                        NRONFS     INTEGER,
                        NRONOT     INTEGER,
                        QTDLIN     INTEGER DEFAULT 0,
                        ID_FINUFE  INTEGER,
                        ID_FINCIE  INTEGER,
                        FLGNFE     CHAR(3),
                        ID_FINPAI  INTEGER,
                        FLGSEL     CHAR(3),
                        IMUEMP     CHAR(18),
                        IGUALAR    SMALLINT,
                        TIPEMP     VARCHAR(30),
                        INSESTST   VARCHAR(20),
                        CONTATO    VARCHAR(28)
);

CREATE TABLE FINREGTRIB (
                            NUMREGTRIB  INTEGER,
                            NOMREGTRIB  VARCHAR(70)
);

CREATE TABLE FINVEN (
                        CODVEN     INTEGER NOT NULL ,
                        NOMVEN     VARCHAR(40),
                        APEVEN     VARCHAR(20),
                        CEPVEN     CHAR(8),
                        ENDVEN     VARCHAR(50),
                        TENVEN     VARCHAR(10),
                        NUMVEN     VARCHAR(10),
                        BAIVEN     VARCHAR(20),
                        CIDVEN     VARCHAR(20),
                        SIGUFE     CHAR(2),
                        CGCVEN     VARCHAR(18),
                        INSVEN     VARCHAR(18),
                        PRFVEN     VARCHAR(4),
                        FONVEN     VARCHAR(20),
                        CODTVE     INTEGER,
                        CODGVE     INTEGER,
                        CODCVE     INTEGER,
                        CODCOM     VARCHAR(3),
                        EMAVEN     VARCHAR(50),
                        WEBVEN     VARCHAR(50),
                        REFVEN     VARCHAR(40),
                        CODBAN     INTEGER,
                        CODAGB     VARCHAR(15),
                        CODCNB     VARCHAR(15),
                        NOMCNB     VARCHAR(50),
                        PFAVEN     VARCHAR(4),
                        FAXVEN     VARCHAR(20),
                        SEQREP     INTEGER DEFAULT 0,
                        FLGTRG     CHAR(1),
                        SLDVEN     NUMERIC(15,2) DEFAULT 0,
                        QTDREP     INTEGER DEFAULT 0,
                        METREP     NUMERIC(15,2) DEFAULT 0,
                        FLGATI     CHAR(3),
                        CODCLP     CHAR(1),
                        DCAVEN     DATE,
                        NOMRES     VARCHAR(40),
                        PRCVEN     CHAR(4),
                        CELVEN     CHAR(20),
                        ID_FINUFE  INTEGER,
                        ID_FINCIE  INTEGER,
                        ID_FINPAI  INTEGER
);

ALTER TABLE FINVEN ADD CONSTRAINT FINVEN_PK PRIMARY KEY (CODVEN);