ALTER TABLE ESTPRO ADD DSCPRO VARCHAR(100);
ALTER TABLE ESTPRO ADD DSRPRO VARCHAR(100);
ALTER TABLE ESTPRO ADD REFPRO VARCHAR(40);
ALTER TABLE ESTPRO ADD CODNCM VARCHAR(20);
ALTER TABLE ESTPRO ADD CEST VARCHAR(10);
ALTER TABLE ESTPRO ADD CODST1 VARCHAR(10);
ALTER TABLE ESTPRO ADD CODCAT VARCHAR(10);
ALTER TABLE ESTPRO ADD CODTIP VARCHAR(10);
ALTER TABLE ESTPRO ADD CODMRC VARCHAR(20);
ALTER TABLE ESTPRO ADD CODUNE VARCHAR(10);
ALTER TABLE ESTPRO ADD CODUNS VARCHAR(10);
ALTER TABLE ESTPRO ADD PESLIQ NUMERIC(15, 4);
ALTER TABLE ESTPRO ADD PESBRT NUMERIC(15, 4);
ALTER TABLE ESTPRO ADD FLBPRO CHAR(1);
ALTER TABLE ESTPRO ADD CBAPRO VARCHAR(30);
ALTER TABLE ESTPRO ADD CODBAR VARCHAR(30);
ALTER TABLE ESTPRO ADD IDEPRO NUMERIC(15, 4);
ALTER TABLE ESTPRO ADD SIMPRO VARCHAR(30);
ALTER TABLE ESTPRO ADD QTDVOL NUMERIC(15, 4);
ALTER TABLE ESTPRO ADD QTDEMB NUMERIC(15, 4);
ALTER TABLE ESTPRO ADD LOCPRO VARCHAR(30);
ALTER TABLE ESTPRO ADD PESCUB NUMERIC(15, 4);
ALTER TABLE ESTPRO ADD CBAEMB VARCHAR(30);
ALTER TABLE ESTPRO ADD IBSCBS_C_CLASS_TRIB VARCHAR(30);
ALTER TABLE ESTPRO ADD IBSCBS_CST VARCHAR(30);
ALTER TABLE ESTPRO ADD COD_FCP_ENTRADA VARCHAR(30);
ALTER TABLE ESTPRO ADD COD_FCP_SAIDA VARCHAR(30);
ALTER TABLE ESTPRO ADD IPISAI VARCHAR(10);
ALTER TABLE ESTPRO ADD IPIENT VARCHAR(10);
ALTER TABLE ESTPRO ADD ICMSAI VARCHAR(10);
ALTER TABLE ESTPRO ADD ICMENT VARCHAR(10);
ALTER TABLE ESTPRO ADD CODSTS VARCHAR(10);
ALTER TABLE ESTPRO ADD CODSTE VARCHAR(10);
ALTER TABLE ESTPRO ADD OBSPRO VARCHAR(1000);

ALTER TABLE PEDRES ADD SITRES VARCHAR(10);
ALTER TABLE PEDRES ADD TOTGER NUMERIC(15, 2);
ALTER TABLE PEDRES ADD TOTRES NUMERIC(15, 2);
ALTER TABLE PEDRES ADD TOTIPI NUMERIC(15, 2);
ALTER TABLE PEDRES ADD TOTICM NUMERIC(15, 2);
ALTER TABLE PEDRES ADD TOTPIS NUMERIC(15, 2);
ALTER TABLE PEDRES ADD TOTCOF NUMERIC(15, 2);
ALTER TABLE PEDRES ADD TOTSUB NUMERIC(15, 2);
ALTER TABLE PEDRES ADD TOTDESCINC NUMERIC(15, 2);
ALTER TABLE PEDRES ADD TOTFRT NUMERIC(15, 2);
ALTER TABLE PEDRES ADD TOTSEG NUMERIC(15, 2);
ALTER TABLE PEDRES ADD TOTOUTDESP NUMERIC(15, 2);
ALTER TABLE PEDRES ADD CODVEN INTEGER;
ALTER TABLE PEDRES ADD CODATD INTEGER;
ALTER TABLE PEDRES ADD DTFRES DATE;
ALTER TABLE PEDRES ADD CODTRA VARCHAR(20);
ALTER TABLE PEDRES ADD PEDANT VARCHAR(20);
ALTER TABLE PEDRES ADD REGTRB INTEGER;
ALTER TABLE PEDRES ADD CODPFA VARCHAR(20);

ALTER TABLE PEDRE2 ADD DESRE2 VARCHAR(100);
ALTER TABLE PEDRE2 ADD QTPRE2 NUMERIC(15, 4);
ALTER TABLE PEDRE2 ADD VLQRE2 NUMERIC(15, 4);
ALTER TABLE PEDRE2 ADD TOTRE2 NUMERIC(15, 4);
ALTER TABLE PEDRE2 ADD CODST1 VARCHAR(10);
ALTER TABLE PEDRE2 ADD CODUND VARCHAR(10);
ALTER TABLE PEDRE2 ADD VLURE2 NUMERIC(15, 4);
ALTER TABLE PEDRE2 ADD DSCRE2 NUMERIC(15, 4);
ALTER TABLE PEDRE2 ADD DSRRE2 NUMERIC(15, 4);
ALTER TABLE PEDRE2 ADD ICMRE2 NUMERIC(15, 4);
ALTER TABLE PEDRE2 ADD BASICM NUMERIC(15, 4);
ALTER TABLE PEDRE2 ADD TOTICM NUMERIC(15, 4);
ALTER TABLE PEDRE2 ADD REDICM NUMERIC(15, 4);
ALTER TABLE PEDRE2 ADD BASSUB NUMERIC(15, 4);
ALTER TABLE PEDRE2 ADD TOTSUB NUMERIC(15, 4);
ALTER TABLE PEDRE2 ADD ICMSUB NUMERIC(15, 4);
ALTER TABLE PEDRE2 ADD MRGSUB NUMERIC(15, 4);
ALTER TABLE PEDRE2 ADD REDSUB NUMERIC(15, 4);
ALTER TABLE PEDRE2 ADD IPIRE2 NUMERIC(15, 4);
ALTER TABLE PEDRE2 ADD BASIPI NUMERIC(15, 4);
ALTER TABLE PEDRE2 ADD TOTIPI NUMERIC(15, 4);
ALTER TABLE PEDRE2 ADD CLSIPI VARCHAR(20);
ALTER TABLE PEDRE2 ADD CSTIPI VARCHAR(10);
ALTER TABLE PEDRE2 ADD BASPIS NUMERIC(15, 4);
ALTER TABLE PEDRE2 ADD ALIQPIS NUMERIC(15, 4);
ALTER TABLE PEDRE2 ADD TOTPIS NUMERIC(15, 4);
ALTER TABLE PEDRE2 ADD CSTPIS VARCHAR(10);
ALTER TABLE PEDRE2 ADD BASCOF NUMERIC(15, 4);
ALTER TABLE PEDRE2 ADD ALIQCOF NUMERIC(15, 4);
ALTER TABLE PEDRE2 ADD TOTCOF NUMERIC(15, 4);
ALTER TABLE PEDRE2 ADD CSTCOF VARCHAR(10);
ALTER TABLE PEDRE2 ADD TOTDSR NUMERIC(15, 4);
ALTER TABLE PEDRE2 ADD TOTFRT NUMERIC(15, 4);
ALTER TABLE PEDRE2 ADD TOTSEG NUMERIC(15, 4);
ALTER TABLE PEDRE2 ADD TOTOUTDESP NUMERIC(15, 4);
ALTER TABLE PEDRE2 ADD TOTITETRB NUMERIC(15, 4);
ALTER TABLE PEDRE2 ADD TOTREN NUMERIC(15, 4);
ALTER TABLE PEDRE2 ADD TOTGE2 NUMERIC(15, 4);
ALTER TABLE PEDRE2 ADD OBSRE2 VARCHAR(1000);
ALTER TABLE PEDRE2 ADD NUMPEDCOMPRA VARCHAR(30);
ALTER TABLE PEDRE2 ADD NUMITEMCOMPRA INTEGER;
ALTER TABLE PEDRE2 ADD NRORE2 INTEGER;
ALTER TABLE PEDRE2 ADD FLGVAL CHAR(1);
ALTER TABLE PEDRE2 ADD FLGPAC CHAR(1);
ALTER TABLE PEDRE2 ADD FLGLIB CHAR(1);
ALTER TABLE PEDRE2 ADD CODCFO VARCHAR(10);
ALTER TABLE PEDRE2 ADD DSPRE2 VARCHAR(100);
ALTER TABLE PEDRE2 ADD LIQRE2 NUMERIC(15, 4);
ALTER TABLE PEDRE2 ADD BRTRE2 NUMERIC(15, 4);
ALTER TABLE PEDRE2 ADD REFRE2 VARCHAR(40);
ALTER TABLE PEDRE2 ADD QTFRE2 NUMERIC(15, 4);
ALTER TABLE PEDRE2 ADD QTSRE2 NUMERIC(15, 4);
ALTER TABLE PEDRE2 ADD TOTCST NUMERIC(15, 4);
ALTER TABLE PEDRE2 ADD LUCROL NUMERIC(15, 4);
ALTER TABLE PEDRE2 ADD LUCROP NUMERIC(15, 4);
ALTER TABLE PEDRE2 ADD SLDRE2 NUMERIC(15, 4);
ALTER TABLE PEDRE2 ADD VDSRE2 NUMERIC(15, 4);
ALTER TABLE PEDRE2 ADD TOTDSC NUMERIC(15, 4);

CREATE TABLE FATPED (
    CODEMP INTEGER NOT NULL,
    DTERES DATE NOT NULL,
    NUMRES INTEGER NOT NULL,
    NRONFS VARCHAR(20),
    DTAFAT DATE,
    TOTFAT NUMERIC(15, 2)
);

CREATE TABLE FINCDE (
    CODCLI INTEGER NOT NULL,
    SEQCDE VARCHAR(20),
    DTECDE TIMESTAMP NOT NULL,
    DTEPED TIMESTAMP,
    VALCDE NUMERIC(15, 2),
    USACDE NUMERIC(15, 2),
    SLDCDE NUMERIC(15, 2),
    SITCDE VARCHAR(10)
);

CREATE TABLE FINPLA (
    CODPLA VARCHAR(20) NOT NULL,
    NOMPLA VARCHAR(100)
);

CREATE TABLE FINCOM (
    CODCOM VARCHAR(20) NOT NULL,
    PERCOM NUMERIC(15, 4)
);

CREATE TABLE FINTDO (
    CODTDO VARCHAR(20) NOT NULL,
    NOMTDO VARCHAR(100)
);

CREATE TABLE FINBAN (
    CODBAN VARCHAR(20) NOT NULL,
    NOMBAN VARCHAR(100)
);

CREATE TABLE FINCRE (
    CODEMP INTEGER NOT NULL,
    DTECRE DATE,
    NUMCRE NUMERIC(15, 0) NOT NULL,
    CODPLA VARCHAR(20),
    CODCOM VARCHAR(20),
    CODCLI INTEGER,
    CODVEN INTEGER,
    CODTDO VARCHAR(20)
);

CREATE TABLE FINCRP (
    CODEMP INTEGER NOT NULL,
    DTECRE DATE,
    NUMCRE NUMERIC(15, 0) NOT NULL,
    NUMCRP INTEGER,
    FLGINC CHAR(1),
    DTEINC DATE,
    DTVCRP DATE,
    PRACRP INTEGER,
    VLPCRP NUMERIC(15, 2),
    NOSNUM VARCHAR(30),
    CODBAN VARCHAR(20),
    OBSCRP VARCHAR(1000),
    FLGANU CHAR(1),
    DTEANU DATE,
    FLPCRP CHAR(1)
);

CREATE TABLE PEDLIB (
    CODEMP INTEGER NOT NULL,
    DTERES DATE,
    NUMRES INTEGER NOT NULL,
    SEQLIB INTEGER NOT NULL,
    DTELIB DATE,
    HRELIB VARCHAR(10),
    CODCLI INTEGER,
    QTSLIB INTEGER,
    TOTLIB NUMERIC(15, 2),
    TOTGER NUMERIC(15, 2),
    SITLIB VARCHAR(10),
    CODVEN INTEGER,
    PCOLIB NUMERIC(15, 4),
    TOTCST NUMERIC(15, 2)
);

CREATE TABLE PEDLB2 (
    CODEMP INTEGER NOT NULL,
    DTERES DATE,
    NUMRES INTEGER NOT NULL,
    SEQLIB INTEGER NOT NULL,
    SEQLB2 INTEGER NOT NULL,
    CODCLP VARCHAR(10),
    CODGRU VARCHAR(10),
    CODSUB VARCHAR(10),
    CODPRO VARCHAR(10),
    DESLB2 VARCHAR(100),
    QTPLB2 NUMERIC(15, 4),
    QTSLB2 NUMERIC(15, 4),
    SLDLB2 NUMERIC(15, 4),
    TOTLB2 NUMERIC(15, 4),
    TOTGE2 NUMERIC(15, 4),
    DSCLB2 NUMERIC(15, 4),
    TOTCST NUMERIC(15, 4),
    PACLB2 NUMERIC(15, 4),
    VLULB2 NUMERIC(15, 4),
    VLQLB2 NUMERIC(15, 4),
    VCSLB2 NUMERIC(15, 4)
);

CREATE TABLE ESTICM (
    CODICM VARCHAR(20) NOT NULL,
    TIPICM VARCHAR(20) NOT NULL,
    NOMICM VARCHAR(100),
    UFEMITENTE VARCHAR(2),
    CODREGTRIB VARCHAR(20),
    PERICM NUMERIC(15, 4),
    REDICM NUMERIC(15, 4),
    BASICM NUMERIC(15, 4),
    CODST2 VARCHAR(20)
);

CREATE TABLE ESTIPI (
    FLGATIVO CHAR(1),
    CODIPI VARCHAR(20) NOT NULL,
    TIPIPI VARCHAR(20) NOT NULL,
    NOMIPI VARCHAR(100),
    CLSIPI VARCHAR(20),
    COD_ENQ VARCHAR(20),
    CSTIPI VARCHAR(20),
    PERIPI NUMERIC(15, 4),
    BASIPI NUMERIC(15, 4),
    FLG_SINEIF20 CHAR(1),
    CODTXF VARCHAR(20),
    CSTPIS VARCHAR(20),
    ALIQ_PIS NUMERIC(15, 4),
    FLG_DESC_ZF_PIS CHAR(1),
    CSTCOF VARCHAR(20),
    ALIQ_COF NUMERIC(15, 4),
    FLG_DESC_ZF_COF CHAR(1)
);

CREATE TABLE ESTSIP (
    SIGNFE VARCHAR(20),
    TIPSIP VARCHAR(20),
    NOMSIP VARCHAR(100)
);

CREATE TABLE ESTPIS (
    SIGNFE VARCHAR(20),
    NOMPIS VARCHAR(100)
);

CREATE TABLE ESTCOF (
    SIGNFE VARCHAR(20),
    NOMCOF VARCHAR(100)
);

CREATE TABLE ESTITE (
    CODCLP INTEGER,
    CODGRU INTEGER,
    CODSUB INTEGER,
    CODPRO INTEGER,
    CODEMP INTEGER,
    VB1ITE NUMERIC(15, 4),
    VB2ITE NUMERIC(15, 4),
    VB3ITE NUMERIC(15, 4),
    VB4ITE NUMERIC(15, 4),
    VB5ITE NUMERIC(15, 4)
);

CREATE TABLE ESTQTE (
    CODCLP INTEGER,
    CODGRU INTEGER,
    CODSUB INTEGER,
    CODPRO INTEGER,
    CODEMP INTEGER,
    QTDQTE NUMERIC(15, 4),
    QTMQTE NUMERIC(15, 4),
    QMAQTE NUMERIC(15, 4),
    QTRQTE NUMERIC(15, 4),
    QTAQTE NUMERIC(15, 4),
    QTDRMA NUMERIC(15, 4)
);

SET TERM ^ ;
CREATE PROCEDURE RESERVAS (
    P_CODEMP INTEGER,
    P_CODCLP INTEGER,
    P_CODGRU INTEGER,
    P_CODSUB INTEGER,
    P_CODPRO INTEGER
)
RETURNS (
    QTD_RESERVADA NUMERIC(15, 4)
)
AS
BEGIN
    QTD_RESERVADA = 0;
    SUSPEND;
END^
SET TERM ; ^
